#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2015 OpenWrt.org

START=98

SERVICE_USE_PID=1

start() {
	/usr/bin/lua /usr/sbin/controller.lua 2>&1 >/dev/null &
}

stop() {
	ps | grep controller.lua | grep -v grep | awk '{print $1}' | xargs kill -9
}
